# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HarnessDeck < Formula
  desc "Unified dashboard for AI coding work across harnesses and projects"
  homepage "https://github.com/TaylorFinklea/harness-deck"
  version "0.1.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TaylorFinklea/harness-deck/releases/download/v0.1.19/harness-deck_0.1.19_darwin_amd64.tar.gz"
      sha256 "46e0988838e302de2091fc8602f1c32302aecc2ffade80e8d812e18a45cb8def"

      define_method(:install) do
        bin.install "harness-deck"
        bin.install_symlink "harness-deck" => "hdeck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TaylorFinklea/harness-deck/releases/download/v0.1.19/harness-deck_0.1.19_darwin_arm64.tar.gz"
      sha256 "83a1f27ec4bdc6ba55294985f7099a87f57556f6f58b20f1b819a439283b1889"

      define_method(:install) do
        bin.install "harness-deck"
        bin.install_symlink "harness-deck" => "hdeck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TaylorFinklea/harness-deck/releases/download/v0.1.19/harness-deck_0.1.19_linux_amd64.tar.gz"
      sha256 "509dbc3b34de1f30ab2d0af9b785cf5480beea73b8d7acd5466aca24d6fd61b9"
      define_method(:install) do
        bin.install "harness-deck"
        bin.install_symlink "harness-deck" => "hdeck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TaylorFinklea/harness-deck/releases/download/v0.1.19/harness-deck_0.1.19_linux_arm64.tar.gz"
      sha256 "e2dc31e112887c99394d8a459ea6ee0de3d3cd9c6c0a310712d6dfebf8d41c02"
      define_method(:install) do
        bin.install "harness-deck"
        bin.install_symlink "harness-deck" => "hdeck"
      end
    end
  end

  test do
    system "#{bin}/harness-deck", "version"
    system "#{bin}/hdeck", "version"
  end
end
